export default function ResultCard({
  result,
  onCopy,
  count,
  maxFree,
}: any) {
  if (!result) {
  return (
    <div className="max-w-md mx-auto mt-10 text-center text-gray-400">
      ✈️ 请输入目的地，开始你的旅行计划
    </div>
  );
}

  return (
    <div className="max-w-md mx-auto mt-6 space-y-4 animate-fade-in">

      {/* Header */}
      <div className="bg-white rounded-3xl shadow p-5 text-center border">
        <p className="text-xs text-gray-400">Generated by</p>
        <h2 className="text-xl font-bold">🌍 TripMuse</h2>
      </div>

      {/* Title */}
      <div className="bg-white rounded-3xl shadow p-5 border">
        <h3 className="font-bold">📍 {result.title}</h3>
        <p className="text-gray-600 text-sm mt-2">{result.overview}</p>
      </div>

      {/* Days */}
      <div className="bg-white rounded-3xl shadow p-5 border">
        <h3 className="font-bold mb-2">🗓 行程</h3>
        {result.days?.map((d: any, i: number) => (
          <div key={i} className="mb-3">
            <p className="font-bold">Day {d.day}</p>
            <p>🌅 {d.morning}</p>
            <p>🌞 {d.afternoon}</p>
            <p>🌙 {d.evening}</p>
            <p className="text-sm text-gray-500">💡 {d.tip}</p>
          </div>
        ))}
      </div>

      {/* Food */}
      <div className="bg-white rounded-3xl shadow p-5 border">
        <h3 className="font-bold mb-2">🍜 美食</h3>
        {result.food?.map((f: string, i: number) => (
          <p key={i}>• {f}</p>
        ))}
      </div>

      {/* Spots */}
      <div className="bg-white rounded-3xl shadow p-5 border">
        <h3 className="font-bold mb-2">📸 打卡</h3>
        {result.spots?.map((s: string, i: number) => (
          <p key={i}>• {s}</p>
        ))}
      </div>

      {/* Tips */}
      <div className="bg-white rounded-3xl shadow p-5 border">
        <h3 className="font-bold mb-2">⚠️ 避坑</h3>
        {result.tips?.map((t: string, i: number) => (
          <p key={i} className="text-red-500">• {t}</p>
        ))}
      </div>

      {/* Budget */}
      <div className="bg-white rounded-3xl shadow p-5 border">
        <h3 className="font-bold mb-2">💰 预算</h3>
        <p>🏨 {result.budget?.hotel}</p>
        <p>🍜 {result.budget?.food}</p>
        <p>🚗 {result.budget?.transport}</p>
        <p>🎫 {result.budget?.ticket}</p>
        <p>🧾 {result.budget?.extra}</p>
      </div>

      {/* Copy */}
      <button
        onClick={onCopy}
        className="w-full bg-black text-white py-2 rounded-xl"
      >
        📋 一键复制
      </button>

      {/* Pro */}
      {count >= maxFree && (
        <div className="bg-yellow-50 border rounded-xl p-4 text-center">
          <p className="font-bold">🔥 升级 Pro</p>
        </div>
      )}
    </div>
  );
}